#
# configure install environment
#

- hosts: head
  become: yes
  become_user: root

  tasks:
  - name: load per node pxe configure
    template:
        src: templates/grub-net.cfg.j2
        dest: /srv/tftpboot/{{ OS_TFTP_TAG }}/net/grub.cfg-01-{{ item.key }}
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ nodes | dict2items }}"

  - name: load per node autoyast install configuration
    template:
        src: templates/localurl-autoinst.xml.j2
        dest: /srv/tftpboot/{{ OS_TFTP_TAG }}/autoyast/{{ node.eth|replace(":", "") }}
        backup: yes
    vars:
        node: "{{ item.value }}"
    loop: "{{ nodes | dict2items }}"